### PR TITLE
Update heroku-java-metrics-agent to 3.11

### PR DESCRIPTION
**Pull request by jkutner**
See also https://github.com/heroku/heroku-java-metrics-agent/pull/7

### CODE REVIEW

**Comment by jtjeferreira** [comment]
Hi @jkutner! 
I noticed this was released, so I redeployed my app and made sure it was using this buildpack, however I still dont see the "JVM: Aggregate Time Spent in Garbage Collection" in heroku dashboard metrics... 

Should I wait a bit more or there is something missing with the PR in heroku/heroku-java-metrics-agent#7?

Nevertheless, thanks for the fast release...

**Comment by jkutner** [comment]
Sorry for the delay here. We had some issues that prevented this from rolling out. We'll be working on it again soon.

**Comment by jtjeferreira** [comment]
> Sorry for the delay here. We had some issues that prevented this from rolling out. We'll be working on it again soon.

Ok. Thanks for the reply

**Comment by jtjeferreira** [comment]
Hi again @jkutner. Any news about this?

**Comment by jkutner** [comment]
@jtjeferreira sorry for my slow response, but I have found the problem. The metrics agent is reporting the CMS data correctly, but a component in Heroku's internal infrastructure is filtering it out before it reaches the dashboard. It will still be a little while before we can roll out the fix. Thank you for your patience!

**Comment by jtjeferreira** [comment]
Hi @jkutner! Thanks for hunting down the problem. Looking forward for the fix... It will be announced in https://devcenter.heroku.com/changelog?

**Comment by jkutner** [comment]
@jtjeferreira yes, I'll also comment back here

**Comment by jkutner** [comment]
@jtjeferreira Please give this a try again, I think you'll find it's working now. Sorry for the delay!

**Comment by jtjeferreira** [comment]
> @jtjeferreira Please give this a try again, I think you'll find it's working now. Sorry for the delay!

I can confirm it's working now

**Pull request merged**
