### PR TITLE
Add legacy functions for backwards compatibility

### PR DESCRIPTION
**Pull request by Malax**
Commit a42a421760174615235f92713d7266a9c133ff8b moved and renamed some functions, breaking backwards compatibility for users of this buildpack as a library. 

Most importantly [heroku-buildpack-play](https://github.com/heroku/heroku-buildpack-play) did [break](https://stackoverflow.com/questions/59407167/heroku-deploy-fails). Granted, it's deprecated, but could work a while longer with this fix. Other buildpacks maintained by third party authors might be affected as well.

I want to add tests for this to avoid regressions. I am not entirely sure what the best way would be. @jkutner, can you share some insight?

### CODE REVIEW

**Comment by tazmaniax** [comment]
@Malax @jkutner thx for making this change! When will it be available at https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz ?

**Comment by Malax** [comment]
@tazmaniax We will roll this out today. I'll update this PR when it's done. :)

**Comment by jkutner** [comment]
@tazmaniax as a side note, I recommend using the URL https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/jvm.tgz if you need to reference the `tgz` directly. We are syncing this location back to `codon-buildpacks`, but eventually we'll deprecate it.

**Comment by tazmaniax** [comment]
@Malax great, thx!

@jkutner right, noticed it was different to what was in the readme. I've made the change in my fork but it was a bit more problematic to make a pull request for the base heroku-buildpack-play as I have other changes in my master

**Comment by tazmaniax** [comment]
Actually looks like I managed to make that pull request :) https://github.com/heroku/heroku-buildpack-play/pull/40

**Comment by Malax** [comment]
@tazmaniax Changes have been rolled out, and thank you for that PR!

**Comment by tazmaniax** [comment]
@Malax tested and working, thanks again!

**Pull request merged**
