### PR TITLE
Download JDK over HTTPS

### LINKED ISSUE #25: JDK is downloaded over HTTP and not separately verified
The JDK is currently downloaded using HTTP rather than HTTPS, and with no validation of hash or signature:
https://github.com/heroku/heroku-buildpack-jvm-common/blob/8d2c2126536f4537f8c3a27e35b1ed5804cb47ba/bin/java#L5-L10
https://github.com/heroku/heroku-buildpack-jvm-common/blob/8d2c2126536f4537f8c3a27e35b1ed5804cb47ba/bin/java#L41-L51

AWS has served working wildcard certs on subdomain S3 buckets for a while now:
```bash
$ echo "Q" | openssl s_client -showcerts -connect lang-jvm.s3.amazonaws.com:443
...
Server certificate
subject=/C=US/ST=Washington/L=Seattle/O=Amazon.com Inc./CN=*.s3.amazonaws.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Baltimore CA-2 G2
...
SSL-Session:
    ...
    Verify return code: 0 (ok)

$ curl -sSfI https://lang-jvm.s3.amazonaws.com/jdk/heroku-16/openjdk1.8.0_121.tar.gz | head -n 1
HTTP/1.1 200 OK
```

Also later in the script `_install_pgconfig()` downloads from the same subdomain over HTTPS, so if there were concerns over older clients without the necessary root stores configured, the script would already be broken for them.

### PR DESCRIPTION
**Pull request by edmorley**
Also adjusts curl usage to output any errors rather than suppress all output.

Fixes #25.

### CODE REVIEW

**Comment by edmorley** [comment]
I believe the Travis failure is unrelated to this PR, but due to PRs from forks not having access to Travis secure environment variables. I've filed #28 for that.

**Comment by edmorley** [comment]
@jkutner I don't suppose you could take a look? :-)

**Comment by jkutner** [comment]
@edmorley yes! missed this one.

**Comment by edmorley** [comment]
Many thanks!

**Pull request merged**
